- name: bug
  color: B60205
  description: "Something isn't working"
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
- name: feature
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: invalid
  color: e4e669
  description: "This doesn't seem right"
- name: question/help
  color: d876e3
  description: Further information or help is requested
- name: wontfix
  color: ffffff
  description: This will not be worked on
- name: packages/better-error
  color: 0E8A16
  description: About better error package
- name: packages/cli
  color: 0E8A16
  description: About cli package
- name: packages/core
  color: 0E8A16
  description: About main package
- name: packages/error
  color: 0E8A16
  description: About error package
- name: packages/dynamic-loader
  color: 0E8A16
  description: About dynamic loaded package
- name: packages/middleware
  color: 0E8A16
  description:
