name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Loading NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Build Packages
        run: pnpm run build
      - name: Run ESLint
        run: pnpm run lint
