name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Loading NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run lint