name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx